use_frameworks!

platform :ios, '8.0'

target 'HCPackView_Example' do
  pod 'HCPackView', :path => '../'

  target 'HCPackView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
